name: limit_rate
description: Guards access to a given resource according to request rate limits.
version: 0.1.0
repository: https://github.com/alexeyinkin/dart-limit-rate

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  clock: ^1.1.0
  collection: ^1.16.0

dev_dependencies:
  fake_async: ^1.3.0
  mocktail: ^0.3.0
  test: ^1.21.1
